USE [RSUD_bengkulu]
GO

/****** Object:  StoredProcedure [dbo].[web_D03_Grafik_Kamar_GKapasitas]    Script Date: 13/03/2018 17:33:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[web_D03_Grafik_Kamar_GKapasitas]
AS  
BEGIN  
SELECT CR.CLINIC_ID,C.NAME_OF_CLINIC,COUNT(BED_ID) as kapasitas
FROM BEDS RIGHT JOIN CLASS_ROOM CR ON BEDS.CLASS_ROOM_ID = CR.CLASS_ROOM_ID
RIGHT JOIN CLINIC C ON CR.CLINIC_ID = C.CLINIC_ID
WHERE C.STYPE_ID IN (3)
GROUP BY CR.CLINIC_ID,C.NAME_OF_CLINIC

END  
GO

