USE [RSUD_bengkulu]
GO

/****** Object:  Table [dbo].[WEBSITE_MENU_TYPE]    Script Date: 13/03/2018 17:22:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WEBSITE_MENU_TYPE](
	[menu_type] [smallint] NOT NULL,
	[menutype] [varchar](50) NULL,
 CONSTRAINT [PK_WEBSITE_MENU_TYPE] PRIMARY KEY CLUSTERED 
(
	[menu_type] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[WEBSITE_MENU_TYPE]  WITH CHECK ADD  CONSTRAINT [FK_WEBSITE_MENU_TYPE_WEBSITE_MENU_TYPE] FOREIGN KEY([menu_type])
REFERENCES [dbo].[WEBSITE_MENU_TYPE] ([menu_type])
GO

ALTER TABLE [dbo].[WEBSITE_MENU_TYPE] CHECK CONSTRAINT [FK_WEBSITE_MENU_TYPE_WEBSITE_MENU_TYPE]
GO


