<?php

namespace App\Models;

use CodeIgniter\Model;

class TreatResultModel extends Model
{
    // protected $org_unit_code = '1771014';
    protected $table      = 'treat_results';
    protected $primaryKey = 'result_id';

    protected $useAutoIncrement = false;

    protected $returnType     = 'array';
    protected $useSoftDeletes = false;

    // protected $allowedFields = ['name', 'email'];
    protected $allowedFields = [
        'org_unit_code',
        'no_registration',
        'visit_id',
        'result_id',
        'clinic_id',
        'bill_id',
        'package_id',
        'tarif_id',
        'tarif_name',
        'employee_id',
        'employee_id_from',
        'pickup_date',
        'reagent_id',
        'bound_id',
        'reagent_name',
        'specimen_id',
        'method_id',
        'conclusion',
        'result_value',
        'measure_id',
        'result_english',
        'measure_english',
        'normal_value',
        'conversion',
        'modified_date',
        'modified_by',
        'description',
        'doctor',
        'doctor_from',
        'status_pasien_id',
        'thename',
        'theaddress',
        'ageyear',
        'agemonth',
        'ageday',
        'theid',
        'gender',
        'isrj',
        'kal_id',
        'treat_image',
        'isnew',
        'isnew_clinic',
        'visit_trans',
        'satuan',
        'satuan_eng',
        'normal_english',
        'desc_english',
        'nota_no',
        'kuitansi_id',
        'file_image',
        'isvalid',
        'iskritis',
        'valid_date',
        'diagnosa_desc',
        'indication_desc',
    ];
    // Dates
    protected $useTimestamps = false;

    public function getTreatResult($nomor, $visit, $tarif)
    {
        $this->select("TREAT_RESULTS.ORG_UNIT_CODE,   
        TREAT_RESULTS.RESULT_ID,   
        TREAT_RESULTS.VISIT_ID,   
        TREAT_RESULTS.NO_REGISTRATION,   
        TREAT_RESULTS.CLINIC_ID,   
        TREAT_RESULTS.BILL_ID,   
        TREAT_RESULTS.PACKAGE_ID,   
        TREAT_RESULTS.TARIF_ID,   
        TREAT_RESULTS.TARIF_NAME,   
        TREAT_RESULTS.EMPLOYEE_ID,   
        TREAT_RESULTS.EMPLOYEE_ID_FROM,   
        TREAT_RESULTS.PICKUP_DATE,   
        TREAT_RESULTS.REAGENT_ID,  
        TREAT_RESULTS.REAGENT_NAME,     
        TREAT_RESULTS.SPECIMEN_ID,   
        TREAT_RESULTS.METHOD_ID,   
        TREAT_RESULTS.CONCLUSION,   
        TREAT_RESULTS.RESULT_VALUE,   
        TREAT_RESULTS.RESULT_ENGLISH,   
        TREAT_RESULTS.NORMAL_VALUE,    
        TREAT_RESULTS.MIN_VALUE,     
        TREAT_RESULTS.MAX_VALUE,    
        TREAT_RESULTS.CONVERSION,   
        TREAT_RESULTS.MODIFIED_DATE,   
        TREAT_RESULTS.MODIFIED_BY,   
        TREAT_RESULTS.DESCRIPTION,   
        TREAT_RESULTS.DOCTOR,   
        TREAT_RESULTS.DOCTOR_FROM,   
        TREAT_RESULTS.STATUS_PASIEN_ID,   
        TREAT_RESULTS.THENAME,   
        TREAT_RESULTS.THEADDRESS,   
        TREAT_RESULTS.AGEYEAR,   
        TREAT_RESULTS.AGEMONTH,   
        TREAT_RESULTS.AGEDAY,   
        TREAT_RESULTS.THEID,   
        TREAT_RESULTS.GENDER,   
        TREAT_RESULTS.ISRJ,   
        TREAT_RESULTS.KAL_ID,   
        TREAT_RESULTS.ISNEW,   
        TREAT_RESULTS.ISNEW_CLINIC,   
        TREAT_RESULTS.VISIT_TRANS,   
        TREAT_RESULTS.REAGENT_NAME,   
        TREAT_RESULTS.BOUND_ID,   
        TREAT_RESULTS.MEASURE_ID,   
        TREAT_RESULTS.MEASURE_ENGLISH,   
        TREAT_RESULTS.SATUAN,   
        TREAT_RESULTS.SATUAN_ENG , 
        TREAT_RESULTS.RESULT_TYPE,
        TREAT_RESULTS.NORMAL_ENGLISH,
        TREAT_RESULTS.DESC_ENGLISH,
         TREAT_RESULTS.PRINT_DATE,
        TREAT_RESULTS.PRINTED_BY,
        TREAT_RESULTS.NOTA_NO,
        TREAT_RESULTS.TREAT_IMAGE,
           TREAT_RESULTS.CLINIC_ID_FROM, TREAT_RESULTS.NOSEP")
            ->where('no_registration', $nomor)
            ->where('visit_id', $visit)
            ->where('tarif_id', $tarif)
            ->orderBy('TREAT_RESULTS.REAGENT_ID, treat_results.bound_id');
        return $this->findAll();
    }
    public function getTreatResultList($nomor, $visit, $clinic_id = null)
    {
        if (!empty($clinic_id)) {
            $this->select("TREAT_RESULTS.ORG_UNIT_CODE,   
            TREAT_RESULTS.RESULT_ID,   
            TREAT_RESULTS.VISIT_ID,   
            TREAT_RESULTS.NO_REGISTRATION,   
            TREAT_RESULTS.CLINIC_ID,   
            TREAT_RESULTS.BILL_ID,   
            TREAT_RESULTS.PACKAGE_ID,   
            TREAT_RESULTS.TARIF_ID,   
            TREAT_RESULTS.TARIF_NAME,   
            TREAT_RESULTS.EMPLOYEE_ID,   
            TREAT_RESULTS.EMPLOYEE_ID_FROM,   
            TREAT_RESULTS.PICKUP_DATE,   
            TREAT_RESULTS.REAGENT_ID,  
            TREAT_RESULTS.REAGENT_NAME,     
            TREAT_RESULTS.SPECIMEN_ID,   
            TREAT_RESULTS.METHOD_ID,   
            TREAT_RESULTS.CONCLUSION,   
            TREAT_RESULTS.RESULT_VALUE,   
            TREAT_RESULTS.RESULT_ENGLISH,   
            TREAT_RESULTS.NORMAL_VALUE,    
            TREAT_RESULTS.MIN_VALUE,     
            TREAT_RESULTS.MAX_VALUE,    
            TREAT_RESULTS.CONVERSION,   
            TREAT_RESULTS.MODIFIED_DATE,   
            TREAT_RESULTS.MODIFIED_BY,   
            TREAT_RESULTS.DESCRIPTION,   
            TREAT_RESULTS.DOCTOR,   
            TREAT_RESULTS.DOCTOR_FROM,   
            TREAT_RESULTS.STATUS_PASIEN_ID,   
            TREAT_RESULTS.THENAME,   
            TREAT_RESULTS.THEADDRESS,   
            TREAT_RESULTS.AGEYEAR,   
            TREAT_RESULTS.AGEMONTH,   
            TREAT_RESULTS.AGEDAY,   
            TREAT_RESULTS.THEID,   
            TREAT_RESULTS.GENDER,   
            TREAT_RESULTS.ISRJ,   
            TREAT_RESULTS.KAL_ID,   
            TREAT_RESULTS.ISNEW,   
            TREAT_RESULTS.ISNEW_CLINIC,   
            TREAT_RESULTS.ISVALID,   
            TREAT_RESULTS.ISKRITIS,   
            TREAT_RESULTS.VISIT_TRANS,   
            TREAT_RESULTS.REAGENT_NAME,   
            TREAT_RESULTS.BOUND_ID,   
            TREAT_RESULTS.MEASURE_ID,   
            TREAT_RESULTS.MEASURE_ENGLISH,   
            TREAT_RESULTS.SATUAN,   
            TREAT_RESULTS.SATUAN_ENG , 
            TREAT_RESULTS.RESULT_TYPE,
            TREAT_RESULTS.NORMAL_ENGLISH,
            TREAT_RESULTS.DESC_ENGLISH,
             TREAT_RESULTS.PRINT_DATE,
            TREAT_RESULTS.PRINTED_BY,
            TREAT_RESULTS.NOTA_NO,
               TREAT_RESULTS.CLINIC_ID_FROM, TREAT_RESULTS.NOSEP")
                ->where('no_registration', $nomor)
                ->where('visit_id', $visit)
                ->where('clinic_id', $clinic_id)
                ->orderBy('TREAT_RESULTS.REAGENT_ID, treat_results.bound_id');
            return $this->findAll();
        } else {
            $this->select("TREAT_RESULTS.ORG_UNIT_CODE,   
            TREAT_RESULTS.RESULT_ID,   
            TREAT_RESULTS.VISIT_ID,   
            TREAT_RESULTS.NO_REGISTRATION,   
            TREAT_RESULTS.CLINIC_ID,   
            TREAT_RESULTS.BILL_ID,   
            TREAT_RESULTS.PACKAGE_ID,   
            TREAT_RESULTS.TARIF_ID,   
            TREAT_RESULTS.TARIF_NAME,   
            TREAT_RESULTS.EMPLOYEE_ID,   
            TREAT_RESULTS.EMPLOYEE_ID_FROM,   
            TREAT_RESULTS.PICKUP_DATE,   
            TREAT_RESULTS.REAGENT_ID,  
            TREAT_RESULTS.REAGENT_NAME,     
            TREAT_RESULTS.SPECIMEN_ID,   
            TREAT_RESULTS.METHOD_ID,   
            TREAT_RESULTS.CONCLUSION,   
            TREAT_RESULTS.RESULT_VALUE,   
            TREAT_RESULTS.RESULT_ENGLISH,   
            TREAT_RESULTS.NORMAL_VALUE,    
            TREAT_RESULTS.MIN_VALUE,     
            TREAT_RESULTS.MAX_VALUE,    
            TREAT_RESULTS.CONVERSION,   
            TREAT_RESULTS.MODIFIED_DATE,   
            TREAT_RESULTS.MODIFIED_BY,   
            TREAT_RESULTS.DESCRIPTION,   
            TREAT_RESULTS.DOCTOR,   
            TREAT_RESULTS.DOCTOR_FROM,   
            TREAT_RESULTS.STATUS_PASIEN_ID,   
            TREAT_RESULTS.THENAME,   
            TREAT_RESULTS.THEADDRESS,   
            TREAT_RESULTS.AGEYEAR,   
            TREAT_RESULTS.AGEMONTH,   
            TREAT_RESULTS.AGEDAY,   
            TREAT_RESULTS.THEID,   
            TREAT_RESULTS.GENDER,   
            TREAT_RESULTS.ISRJ,   
            TREAT_RESULTS.KAL_ID,   
            TREAT_RESULTS.ISNEW,   
            TREAT_RESULTS.ISNEW_CLINIC, 
            TREAT_RESULTS.ISVALID,   
            TREAT_RESULTS.ISKRITIS,     
            TREAT_RESULTS.VISIT_TRANS,   
            TREAT_RESULTS.REAGENT_NAME,   
            TREAT_RESULTS.BOUND_ID,   
            TREAT_RESULTS.MEASURE_ID,   
            TREAT_RESULTS.MEASURE_ENGLISH,   
            TREAT_RESULTS.SATUAN,   
            TREAT_RESULTS.SATUAN_ENG , 
            TREAT_RESULTS.RESULT_TYPE,
            TREAT_RESULTS.NORMAL_ENGLISH,
            TREAT_RESULTS.DESC_ENGLISH,
             TREAT_RESULTS.PRINT_DATE,
            TREAT_RESULTS.PRINTED_BY,
            TREAT_RESULTS.NOTA_NO,
               TREAT_RESULTS.CLINIC_ID_FROM, TREAT_RESULTS.NOSEP")
                ->where('no_registration', $nomor)
                ->where('visit_id', $visit)
                ->orderBy('TREAT_RESULTS.REAGENT_ID, treat_results.bound_id');
            return $this->findAll();
        }
    }
}
